# Generated by Django 3.0.3 on 2020-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='contract_date',
            new_name='partnered_on',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_top',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='support_mail',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='support_no',
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(default='India', max_length=200),
        ),
        migrations.AddField(
            model_name='seller',
            name='delivery_in',
            field=models.CharField(default='10days', max_length=30),
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(default='none', max_length=254),
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
