# Generated by Django 3.0.3 on 2020-07-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200719_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Lenovo', 'Lenovo'), ('Oneplus', 'Oneplus'), ('Apple', 'Apple'), ('jbl', 'jbl'), ('Dell', 'Dell'), ('HP', 'HP'), ('bose', 'bose')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Earphones', 'Earphones'), ('Smartphone', 'Smartphone'), ('Accessories', 'Accessories'), ('Laptops', 'Laptops')], default='Accessories', max_length=200),
        ),
    ]
