# Generated by Django 3.0.3 on 2020-07-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200719_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo_main',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='photo_1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='photo_2',
            new_name='image_2',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('jbl', 'jbl'), ('Samsung', 'Samsung'), ('bose', 'bose'), ('Lenovo', 'Lenovo'), ('Dell', 'Dell'), ('Apple', 'Apple'), ('Oneplus', 'Oneplus'), ('HP', 'HP')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Earphones', 'Earphones'), ('Smartphone', 'Smartphone'), ('Accessories', 'Accessories')], default='Accessories', max_length=200),
        ),
    ]
