# Generated by Django 3.0.3 on 2020-07-20 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20200720_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Oneplus', 'Oneplus'), ('HP', 'HP'), ('Samsung', 'Samsung'), ('Lenovo', 'Lenovo'), ('bose', 'bose'), ('jbl', 'jbl'), ('Dell', 'Dell')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Earphones', 'Earphones'), ('Laptops', 'Laptops'), ('Smartphone', 'Smartphone'), ('Accessories', 'Accessories')], default='Accessories', max_length=200),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', django_mysql.models.ListTextField(models.IntegerField(), blank=True, size=10)),
                ('quantity', django_mysql.models.ListTextField(models.IntegerField(), blank=True, size=10)),
                ('amount', django_mysql.models.ListTextField(models.IntegerField(), blank=True, size=11)),
                ('list_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
