# Generated by Django 3.0.3 on 2020-07-20 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_auto_20200720_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Oneplus', 'Oneplus'), ('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Apple', 'Apple'), ('Samsung', 'Samsung'), ('bose', 'bose'), ('jbl', 'jbl')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Earphones', 'Earphones'), ('Laptops', 'Laptops'), ('Smartphone', 'Smartphone')], default='Accessories', max_length=200),
        ),
    ]
