# Generated by Django 3.0.3 on 2020-07-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200720_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Oneplus', 'Oneplus'), ('Samsung', 'Samsung'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('bose', 'bose'), ('jbl', 'jbl'), ('Dell', 'Dell'), ('Apple', 'Apple')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Smartphone', 'Smartphone'), ('Earphones', 'Earphones'), ('Laptops', 'Laptops')], default='Accessories', max_length=200),
        ),
    ]
