# Generated by Django 3.0.3 on 2020-07-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200721_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('jbl', 'jbl'), ('Lenovo', 'Lenovo'), ('HP', 'HP'), ('Samsung', 'Samsung'), ('Dell', 'Dell'), ('Apple', 'Apple'), ('Oneplus', 'Oneplus'), ('bose', 'bose')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Earphones', 'Earphones'), ('Smartphone', 'Smartphone'), ('Accessories', 'Accessories')], default='Accessories', max_length=200),
        ),
    ]
